title = 'Configuration file of the DAQmx plugin'

[NIDAQ_Devices]

[NIDAQ_Devices.DEVICE01]
title = "Configuration entry for a NIDAQmx device"
name = ""
product = ""

[NIDAQ_Devices.DEVICE02_Example]
title = "Configuration entry for a NIDAQmx device"
name = "cDAQ1"
product = "cDAQ-9174"

[NIDAQ_Devices.DEVICE01.MODULE01]
title = "A module plugged in the NIDAQmx device"
name = ""
product = ""

[NIDAQ_Devices.DEVICE01.MODULE02_Example]
title = "A module plugged in a NIDAQmx device"
name = "cDAQMod1"
product = "NI 9211"

[NIDAQ_Devices.DEVICE01.MODULE01.ai]

[NIDAQ_Devices.DEVICE01.MODULE01.ai.ai_current_Example]
info = "Replace ai_current_Example by the channel id such as ai02"
source = 'ANALOG_INPUT'
analog_type = 'CURRENT'
value_min = 0
value_max = 1
termination = "RSE"

[NIDAQ_Devices.DEVICE01.MODULE01.ai.ai_voltage_Example]
info = "Replace ai_voltage_Example by the channel id such as ai02"
source = 'ANALOG_INPUT'
analog_type = 'VOLTAGE'
value_min = -10
value_max = 10
termination = "RSE"

[NIDAQ_Devices.DEVICE01.MODULE01.ai.ai_thrmcpl_Example]
info = "Replace ai_thrmcpl_Example by the channel id such as ai02"
source = 'ANALOG_INPUT'
analog_type = 'TEMPERATURE_THERMOCOUPLE'
thermo_type = "K"
value_min = 0
value_max = 100